# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: GateKV-storage.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'GateKV-storage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14GateKV-storage.proto\x12\x0egatekv_storage\"W\n\x0fRegisterRequest\x12\r\n\x05\x61lias\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\'\n\x06sender\x18\x03 \x01(\x0b\x32\x17.gatekv_storage.Address\"!\n\x10RegisterResponse\x12\r\n\x05\x61lias\x18\x01 \x01(\t\"(\n\nSetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x1e\n\x0bSetResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x19\n\nGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"<\n\x0bGetResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x12\n\x05value\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_value\"\x19\n\nRemRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x1e\n\x0bRemResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x07\n\x05\x45mpty\"%\n\x07\x41\x64\x64ress\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\r2\xed\x03\n\x0eGateKV_Storage\x12O\n\x08Register\x12\x1f.gatekv_storage.RegisterRequest\x1a .gatekv_storage.RegisterResponse\"\x00\x12:\n\x03Set\x12\x1a.gatekv_storage.SetRequest\x1a\x15.gatekv_storage.Empty\"\x00\x12@\n\x03Get\x12\x1a.gatekv_storage.GetRequest\x1a\x1b.gatekv_storage.GetResponse\"\x00\x12:\n\x03Rem\x12\x1a.gatekv_storage.RemRequest\x1a\x15.gatekv_storage.Empty\"\x00\x12\x44\n\x07SetData\x12\x1a.gatekv_storage.SetRequest\x1a\x1b.gatekv_storage.SetResponse\"\x00\x12\x44\n\x07GetData\x12\x1a.gatekv_storage.GetRequest\x1a\x1b.gatekv_storage.GetResponse\"\x00\x12\x44\n\x07RemData\x12\x1a.gatekv_storage.RemRequest\x1a\x1b.gatekv_storage.RemResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GateKV_storage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=40
  _globals['_REGISTERREQUEST']._serialized_end=127
  _globals['_REGISTERRESPONSE']._serialized_start=129
  _globals['_REGISTERRESPONSE']._serialized_end=162
  _globals['_SETREQUEST']._serialized_start=164
  _globals['_SETREQUEST']._serialized_end=204
  _globals['_SETRESPONSE']._serialized_start=206
  _globals['_SETRESPONSE']._serialized_end=236
  _globals['_GETREQUEST']._serialized_start=238
  _globals['_GETREQUEST']._serialized_end=263
  _globals['_GETRESPONSE']._serialized_start=265
  _globals['_GETRESPONSE']._serialized_end=325
  _globals['_REMREQUEST']._serialized_start=327
  _globals['_REMREQUEST']._serialized_end=352
  _globals['_REMRESPONSE']._serialized_start=354
  _globals['_REMRESPONSE']._serialized_end=384
  _globals['_EMPTY']._serialized_start=386
  _globals['_EMPTY']._serialized_end=393
  _globals['_ADDRESS']._serialized_start=395
  _globals['_ADDRESS']._serialized_end=432
  _globals['_GATEKV_STORAGE']._serialized_start=435
  _globals['_GATEKV_STORAGE']._serialized_end=928
# @@protoc_insertion_point(module_scope)
