# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import GateKV_storage_pb2 as GateKV__storage__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in GateKV_storage_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GateKV_StorageStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/gatekv_storage.GateKV_Storage/Register',
                request_serializer=GateKV__storage__pb2.RegisterRequest.SerializeToString,
                response_deserializer=GateKV__storage__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.Set = channel.unary_unary(
                '/gatekv_storage.GateKV_Storage/Set',
                request_serializer=GateKV__storage__pb2.SetRequest.SerializeToString,
                response_deserializer=GateKV__storage__pb2.Empty.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/gatekv_storage.GateKV_Storage/Get',
                request_serializer=GateKV__storage__pb2.GetRequest.SerializeToString,
                response_deserializer=GateKV__storage__pb2.GetResponse.FromString,
                _registered_method=True)
        self.Rem = channel.unary_unary(
                '/gatekv_storage.GateKV_Storage/Rem',
                request_serializer=GateKV__storage__pb2.RemRequest.SerializeToString,
                response_deserializer=GateKV__storage__pb2.Empty.FromString,
                _registered_method=True)
        self.SetData = channel.unary_unary(
                '/gatekv_storage.GateKV_Storage/SetData',
                request_serializer=GateKV__storage__pb2.SetRequest.SerializeToString,
                response_deserializer=GateKV__storage__pb2.SetResponse.FromString,
                _registered_method=True)
        self.GetData = channel.unary_unary(
                '/gatekv_storage.GateKV_Storage/GetData',
                request_serializer=GateKV__storage__pb2.GetRequest.SerializeToString,
                response_deserializer=GateKV__storage__pb2.GetResponse.FromString,
                _registered_method=True)
        self.RemData = channel.unary_unary(
                '/gatekv_storage.GateKV_Storage/RemData',
                request_serializer=GateKV__storage__pb2.RemRequest.SerializeToString,
                response_deserializer=GateKV__storage__pb2.RemResponse.FromString,
                _registered_method=True)


class GateKV_StorageServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Set(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GateKV_StorageServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=GateKV__storage__pb2.RegisterRequest.FromString,
                    response_serializer=GateKV__storage__pb2.RegisterResponse.SerializeToString,
            ),
            'Set': grpc.unary_unary_rpc_method_handler(
                    servicer.Set,
                    request_deserializer=GateKV__storage__pb2.SetRequest.FromString,
                    response_serializer=GateKV__storage__pb2.Empty.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=GateKV__storage__pb2.GetRequest.FromString,
                    response_serializer=GateKV__storage__pb2.GetResponse.SerializeToString,
            ),
            'Rem': grpc.unary_unary_rpc_method_handler(
                    servicer.Rem,
                    request_deserializer=GateKV__storage__pb2.RemRequest.FromString,
                    response_serializer=GateKV__storage__pb2.Empty.SerializeToString,
            ),
            'SetData': grpc.unary_unary_rpc_method_handler(
                    servicer.SetData,
                    request_deserializer=GateKV__storage__pb2.SetRequest.FromString,
                    response_serializer=GateKV__storage__pb2.SetResponse.SerializeToString,
            ),
            'GetData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetData,
                    request_deserializer=GateKV__storage__pb2.GetRequest.FromString,
                    response_serializer=GateKV__storage__pb2.GetResponse.SerializeToString,
            ),
            'RemData': grpc.unary_unary_rpc_method_handler(
                    servicer.RemData,
                    request_deserializer=GateKV__storage__pb2.RemRequest.FromString,
                    response_serializer=GateKV__storage__pb2.RemResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gatekv_storage.GateKV_Storage', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gatekv_storage.GateKV_Storage', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GateKV_Storage(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gatekv_storage.GateKV_Storage/Register',
            GateKV__storage__pb2.RegisterRequest.SerializeToString,
            GateKV__storage__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Set(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gatekv_storage.GateKV_Storage/Set',
            GateKV__storage__pb2.SetRequest.SerializeToString,
            GateKV__storage__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gatekv_storage.GateKV_Storage/Get',
            GateKV__storage__pb2.GetRequest.SerializeToString,
            GateKV__storage__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Rem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gatekv_storage.GateKV_Storage/Rem',
            GateKV__storage__pb2.RemRequest.SerializeToString,
            GateKV__storage__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gatekv_storage.GateKV_Storage/SetData',
            GateKV__storage__pb2.SetRequest.SerializeToString,
            GateKV__storage__pb2.SetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gatekv_storage.GateKV_Storage/GetData',
            GateKV__storage__pb2.GetRequest.SerializeToString,
            GateKV__storage__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gatekv_storage.GateKV_Storage/RemData',
            GateKV__storage__pb2.RemRequest.SerializeToString,
            GateKV__storage__pb2.RemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
