# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: GateKV-user.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'GateKV-user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11GateKV-user.proto\x12\x0bgatekv_user\"\x1e\n\x0bSetResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"-\n\x0bGetResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05value\x18\x02 \x01(\t\"\x1e\n\x0bRemResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x07\n\x05\x45mpty2\xbe\x01\n\x0bGateKV_User\x12\x39\n\x07RecvSet\x12\x18.gatekv_user.SetResponse\x1a\x12.gatekv_user.Empty\"\x00\x12\x39\n\x07RecvGet\x12\x18.gatekv_user.GetResponse\x1a\x12.gatekv_user.Empty\"\x00\x12\x39\n\x07RecvRem\x12\x18.gatekv_user.RemResponse\x1a\x12.gatekv_user.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GateKV_user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SETRESPONSE']._serialized_start=34
  _globals['_SETRESPONSE']._serialized_end=64
  _globals['_GETRESPONSE']._serialized_start=66
  _globals['_GETRESPONSE']._serialized_end=111
  _globals['_REMRESPONSE']._serialized_start=113
  _globals['_REMRESPONSE']._serialized_end=143
  _globals['_EMPTY']._serialized_start=145
  _globals['_EMPTY']._serialized_end=152
  _globals['_GATEKV_USER']._serialized_start=155
  _globals['_GATEKV_USER']._serialized_end=345
# @@protoc_insertion_point(module_scope)
