# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import GateKV_user_pb2 as GateKV__user__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in GateKV_user_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GateKV_UserStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecvSet = channel.unary_unary(
                '/gatekv_user.GateKV_User/RecvSet',
                request_serializer=GateKV__user__pb2.SetResponse.SerializeToString,
                response_deserializer=GateKV__user__pb2.Empty.FromString,
                _registered_method=True)
        self.RecvGet = channel.unary_unary(
                '/gatekv_user.GateKV_User/RecvGet',
                request_serializer=GateKV__user__pb2.GetResponse.SerializeToString,
                response_deserializer=GateKV__user__pb2.Empty.FromString,
                _registered_method=True)
        self.RecvRem = channel.unary_unary(
                '/gatekv_user.GateKV_User/RecvRem',
                request_serializer=GateKV__user__pb2.RemResponse.SerializeToString,
                response_deserializer=GateKV__user__pb2.Empty.FromString,
                _registered_method=True)


class GateKV_UserServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RecvSet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecvGet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecvRem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GateKV_UserServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecvSet': grpc.unary_unary_rpc_method_handler(
                    servicer.RecvSet,
                    request_deserializer=GateKV__user__pb2.SetResponse.FromString,
                    response_serializer=GateKV__user__pb2.Empty.SerializeToString,
            ),
            'RecvGet': grpc.unary_unary_rpc_method_handler(
                    servicer.RecvGet,
                    request_deserializer=GateKV__user__pb2.GetResponse.FromString,
                    response_serializer=GateKV__user__pb2.Empty.SerializeToString,
            ),
            'RecvRem': grpc.unary_unary_rpc_method_handler(
                    servicer.RecvRem,
                    request_deserializer=GateKV__user__pb2.RemResponse.FromString,
                    response_serializer=GateKV__user__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gatekv_user.GateKV_User', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gatekv_user.GateKV_User', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GateKV_User(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RecvSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gatekv_user.GateKV_User/RecvSet',
            GateKV__user__pb2.SetResponse.SerializeToString,
            GateKV__user__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecvGet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gatekv_user.GateKV_User/RecvGet',
            GateKV__user__pb2.GetResponse.SerializeToString,
            GateKV__user__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecvRem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gatekv_user.GateKV_User/RecvRem',
            GateKV__user__pb2.RemResponse.SerializeToString,
            GateKV__user__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
